server:
  port: 8808


spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true

      routes:
        - id: user-services
          uri: http://127.0.0.1:8800
          predicates:
            - Path=/user-services/**
          filters:
            - StripPrefix=1  #过滤第一层路径
        - id: admin-services
          uri: http://127.0.0.1:8801
          predicates:
            - Path=/admin-services/**
          filters:
            - StripPrefix=1  #过滤第一层路径
